version: '2'

#same as 
# $(pwd) or ${pwd}
# docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

services:
  jekyll:
    image: bettfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '80:4000'